// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_ from "./routes/[slug].tsx"
import * as $_404 from "./routes/_404.tsx"
import * as $_app from "./routes/_app.tsx"
import * as $archive from "./routes/archive.tsx"
import * as $index from "./routes/index.tsx"
import * as $resume from "./routes/resume.ts"
import * as $rss_xml from "./routes/rss.xml.ts"
import * as $sitemap_xml from "./routes/sitemap.xml.ts"

import { type Manifest } from "$fresh/server.ts"

const manifest = {
  routes: {
    "./routes/[slug].tsx": $_slug_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/archive.tsx": $archive,
    "./routes/index.tsx": $index,
    "./routes/resume.ts": $resume,
    "./routes/rss.xml.ts": $rss_xml,
    "./routes/sitemap.xml.ts": $sitemap_xml,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
